### ISSUE TITLE
Have python compiled and tested on macOS Sierra.

### ISSUE THREAD

**Issue by dispera** [chevah/python-package#59]
To continue the discussion from chevah/onboarding#26

I also tried on macOS sierra and I am getting an error when trying to compile:
```bash
Writing /Users/diego/Work/Chevah/python-package/build/python2.7-osx108-x64/lib/python2.7/site-packages/pysqlite-2.6.3-py2.7.egg-info
~/Work/Chevah/python-package
Traceback (most recent call last):
  File "python-modules/get-pip.py", line 17759, in <module>
    main()
  File "python-modules/get-pip.py", line 162, in main
    bootstrap(tmpdir=tmpdir)
  File "python-modules/get-pip.py", line 82, in bootstrap
    import pip
  File "/var/folders/qg/5w7bsyhn0fzc3mfpbzc2hcrm0000gn/T/tmpizsb5Q/pip.zip/pip/__init__.py", line 15, in <module>
  File "/var/folders/qg/5w7bsyhn0fzc3mfpbzc2hcrm0000gn/T/tmpizsb5Q/pip.zip/pip/vcs/subversion.py", line 9, in <module>
  File "/var/folders/qg/5w7bsyhn0fzc3mfpbzc2hcrm0000gn/T/tmpizsb5Q/pip.zip/pip/index.py", line 30, in <module>
  File "/var/folders/qg/5w7bsyhn0fzc3mfpbzc2hcrm0000gn/T/tmpizsb5Q/pip.zip/pip/wheel.py", line 35, in <module>
  File "/var/folders/qg/5w7bsyhn0fzc3mfpbzc2hcrm0000gn/T/tmpizsb5Q/pip.zip/pip/_vendor/distlib/scripts.py", line 14, in <module>
  File "/var/folders/qg/5w7bsyhn0fzc3mfpbzc2hcrm0000gn/T/tmpizsb5Q/pip.zip/pip/_vendor/distlib/compat.py", line 31, in <module>
ImportError: cannot import name HTTPSHandler
PWD : /Users/diego/Work/Chevah/python-package
Fail: /Users/diego/Work/Chevah/python-package/build/python2.7-osx108-x64/bin/python python-modules/get-pip.py -i http://pypi.chevah.com/simple --trusted-host=pypi.chevah.com
```

I am searching about that HTTPSHandler import error, and it seems related to the openssl package.

I tried with python 2.7.10 and 2.7.12, and reinstalling it and openssl package but it still does not compile.

**Comment by dispera** [comment]
Regarding if I tested it on a VM - no, it is my working system. From my experience with the previous OSX version (Yosemite), running it on a VM was very sluggish as since that version and including Sierra, it limits the graphics to a 128MB card, which is what the OSX guest recognizes, no matter which card. 
So for me it was unusable as it could hang for a minute in the Launchpad for example, but for compiling it should work OK. I worked better if run in headless mode and remoting into it with vnc por example.
I used VMWare workstation at that time, but VirtualBox had the same issue from what I read.

I started the download of Sierra Installer from the App store, so I can create a VM and share it with you some day overnight (when I upgraded from Yosemite, the Sierra installer was removed) - or even faster, share the .iso and install it on a VM if you provide access to it only.

**Comment by adiroiban** [comment]
I prefer a VirtualBox export VM ... with the system settings + virtual HDD

The title of this ticket should be 'Have python compiled and tested on macOS Sierra' or something like that

**Comment by dispera** [comment]
I see - took note of the ticket format for next time :)

No problem, it will be a VirtualBox export then.

**Comment by adiroiban** [comment]
so, first we need

* Sierra VM template configured for perfect os
* Sierra buildslave VM set up with the right access and IP address

After that we can look at updating support for Sierra

please open tickets in trac for each task

**Comment by dispera** [comment]
Being followed up on Trac ticket #3723
